name: "Deploy"

on:
  push:
    tags:
    - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    env:
      SKIP_PREFLIGHT_CHECK: true

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: ./login ${{ secrets.NPM_ACCESS_KEY }} ${{ secrets.FONTAWESOME_REGISTRY }}
    - run: yarn
    - run: yarn run build
    - run: yarn run lint
    - run: ROCKSET_APIKEY="${{ secrets.ROCKSET_APIKEY }}" ROCKSET_APISERVER="${{ secrets.ROCKSET_APISERVER }}" yarn run test
    - run: git checkout -- .
    - run: ./login ${{ secrets.NPM_ACCESS_KEY }} ${{ secrets.FONTAWESOME_REGISTRY }}
    - run: ./lerna-publish
    - run: cd packages/cli && yarn run oclif-pack
    - run: cd packages/cli && oclif promote --sha="${GITHUB_SHA::7}" --version="${GITHUB_REF_NAME:1}"
      env:
        CI: true
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        ROCKSET_APIKEY: ${{ secrets.ROCKSET_APIKEY }}
        ROCKSET_APISERVER: ${{ secrets.ROCKSET_APISERVER }}
